### ISSUE TITLE
Error in install.sh: aarch64 =/= arch64

### ISSUE THREAD

**Issue by duracell** [zauceee/PPLGPwn#15]
Hey, stumbled over this bug in the install script:
```
elif [ $cpu_arch = "aarch64" ]; then
mv ./PPLGPwn-main/pppwn-aarch64 ./PPLGPwn-main/pppwn && rm ./PPLGPwn-main/pppwn-armv7
```
You're referring to "pppwn-aarch64", but the file is named "pppwn-arch64" with one a.
So you should change the filename or the install script.
Because of this the program isn't working if it's not fixed.

Thanks for your work!

**Comment by ayala** [comment]
yeah I had to do this manually, but still can't get past "Sending IPCP configure ACK..". panics and shuts off my PS4 every time. 😔

**Comment by duracell** [comment]
Same here, my ps4 fat (9.0) also crashes always on one specific point on my LG C1. I already replaced the binary itself and the stages, but if I use this script it crashes. If I use the same windows version with the same stages it doesn't work often because it can't find corrupted sections, but then I can always restart the script and if it finds them, the script works without any problem.
I don't understand how it can be this different.

**Comment by zauceee** [comment]
Fixed! Also the fact that both of your ps4's crash Is probably due to them being anti-pppwn probably

**Comment by duracell** [comment]
> Is probably due to them being anti-pppwn probably

What does that mean?
As mentioned, if I use this with my (windows) PC it worked without any crash.
But will try the new version and hope for the best.
