### ISSUE TITLE
It should be working on a rooted android device right how can i fix this issue

### ISSUE THREAD

**Issue by YasefDogan** [zauceee/PPLGPwn#4]
~/.../shared/lgtv $ wget https://github.com/zauceee/PPLGPwn/archive/refs/heads/main.zip
The program wget is not installed. Install it by executing:
 pkg install wget
~/.../shared/lgtv $ pkg install wget
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://packages.termux.org/apt/termux-main/: ok
Hit:2 https://packages-cf.termux.dev/apt/termux-root root InRelease
Hit:3 https://packages-cf.termux.dev/apt/termux-x11 x11 InRelease
Hit:1 https://packages.termux.dev/apt/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libuuid
The following NEW packages will be installed:
  libuuid wget
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 300 kB of archives.
After this operation, 905 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages.termux.dev/apt/termux-main stable/main aarch64 libuuid aarch64 2.39.3-4 [14.6 kB]
Get:2 https://packages.termux.dev/apt/termux-main stable/main aarch64 wget aarch64 1.24.5 [286 kB]
Fetched 300 kB in 1s (235 kB/s)
Selecting previously unselected package libuuid.
(Reading database ... 20788 files and directories currently installed.)
Preparing to unpack .../libuuid_2.39.3-4_aarch64.deb ...
Unpacking libuuid (2.39.3-4) ...
Selecting previously unselected package wget.
Preparing to unpack .../wget_1.24.5_aarch64.deb ...
Unpacking wget (1.24.5) ...
Setting up libuuid (2.39.3-4) ...
Setting up wget (1.24.5) ...
~/.../shared/lgtv $ wget https://github.com/zauceee/PPLGPwn/archive/refs/heads/main.zip
--2024-05-13 19:31:20--  https://github.com/zauceee/PPLGPwn/archive/refs/heads/main.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/zauceee/PPLGPwn/zip/refs/heads/main [following]
--2024-05-13 19:31:20--  https://codeload.github.com/zauceee/PPLGPwn/zip/refs/heads/main
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘main.zip’

main.zip           405.33K   188KB/s    in 2.2s

2024-05-13 19:31:24 (188 KB/s) - ‘main.zip’ saved [415060]

~/.../shared/lgtv $ unzip main.zip
Archive:  main.zip
719f43c2baa766a55f152ba0e2821f3033749710
   creating: PPLGPwn-main/
  inflating: PPLGPwn-main/LICENSE.txt
  inflating: PPLGPwn-main/README.md
  inflating: PPLGPwn-main/pppwn
  inflating: PPLGPwn-main/stage1.bin
  inflating: PPLGPwn-main/stage2.bin
  inflating: PPLGPwn-main/start.sh
~/.../shared/lgtv $ cd PPLGPwn-main
~/.../lgtv/PPLGPwn-main $ chmod +x ./start.sh
~/.../lgtv/PPLGPwn-main $ ./start.sh
bash: ./start.sh: Permission denied
~/.../lgtv/PPLGPwn-main $ /start.sh
bash: /start.sh: No such file or directory
~/.../lgtv/PPLGPwn-main $ start.sh
No command start.sh found, did you mean:
 Command states in package enscript
~/.../lgtv/PPLGPwn-main $ su
:/data/data/com.termux/files/home/storage/shared/lgtv/PPLGPwn-main # ls
LICENSE.txt  pppwn       stage2.bin
README.md    stage1.bin  start.sh
:/data/data/com.termux/files/home/storage/shared/lgtv/PPLGPwn-main # ./start.sh
/system/bin/sh: ./start.sh: can't execute: Permission denied
126|:/data/data/com.termux/files/home/storage/shared/lgtv/PPLGPwn-main # -

**Comment by llbranco** [comment]
this is made for LG TV WebOS **ONLY**

for Android devices check:
https://github.com/Dark-life944/PPPwn-Android
Keep in mind that Android phones and TVs have some differences and even the Android build _may not work_ on Android TV

Furthermore, keep in mind that our project is still in its early stages.
That said, it is possible that glitches, bugs or compatibility issues may appear on some devices... anyway, thanks for reporting.
