### ISSUE TITLE
Wget Error

### ISSUE THREAD

**Issue by AJhacks101** [zauceee/PPLGPwn#7]
Wget: not an http or ftp url

**Comment by zauceee** [comment]
In which step are you getting this error?

**Comment by llbranco** [comment]
post a log or screenshot of your error
you using linux, windows, mac? terminal, putty, dev-manager-desktop?
running the script connected to your tv, right? is it webos?

**Comment by FabulosoDev** [comment]
Hi everyone,

I was facing the same issue on my TV oled b7d and fixed it by using curl instead of wget.

give that a try:
`curl -k -L -O https://github.com/zauceee/PPLGPwn/releases/download/v1.2/install.sh && chmod +x ./install.sh && ./install.sh`

**Comment by FabulosoDev** [comment]
I also had problems unzipping the zip file. That's why I adapted the `install.sh` in my fork. It now loads the required files individually from the `main` branch

**Comment by zauceee** [comment]
It occurred that the Wget error was due to some problem in the GitHub servers, which affected all repos, it should work normally now.

**Comment by zauceee** [comment]
> I also had problems unzipping the zip file. That's why I adapted the `install.sh` in my fork. It now loads the required files individually from the `main` branch

That's due to some weird thing that curl does while downloading files, thus why I used Wget, which downloads the files properly

**Comment by FabulosoDev** [comment]
> > I also had problems unzipping the zip file. That's why I adapted the `install.sh` in my fork. It now loads the required files individually from the `main` branch
> 
> That's due to some weird thing that curl does while downloading files, thus why I used Wget, which downloads the files properly

thanks for that info, will give that a try later on 👍

**Comment by zauceee** [comment]
> > > I also had problems unzipping the zip file. That's why I adapted the `install.sh` in my fork. It now loads the required files individually from the `main` branch
> > 
> > That's due to some weird thing that curl does while downloading files, thus why I used Wget, which downloads the files properly
> 
> thanks for that info, will give that a try later on 👍

Sem problema irmão!😁

**Comment by gman234595** [comment]
The curl does not fix the problem. I get the below response.

Downloading files...
-------

wget: not an http or ftp url: https://github.com/zauceee/PPLGPwn/archive/refs/heads/main.zip
Done!

-------
Setting up files...
-------

unzip: can't open main.zip[.zip]
mv: can't rename './PPLGPwn-main/pppwn-armv7': No such file or directory
mv: can't rename './PPLGPwn-main': No such file or directory
Done!

-------
CONFIGURATION
-------

Do you want PPLGPwn to run when your TV is turned on? (TV will reboot to apply this setting)
(WARNING!: Running the same payload everytime, can cause your PS4 to crash, proceed with caution.) [y/N]

**Comment by gman234595** [comment]
> curl -k -L -O https://github.com/zauceee/PPLGPwn/releases/download/v1.2/install.sh && chmod +x ./install.sh && ./install.sh

Thank you, but the issue is the same I get the below response. 

Downloading files...
-------

wget: not an http or ftp url: https://github.com/zauceee/PPLGPwn/archive/refs/heads/main.zip
Done!

-------
Setting up files...
-------

unzip: can't open main.zip[.zip]
mv: can't rename './PPLGPwn-main/pppwn-armv7': No such file or directory
mv: can't rename './PPLGPwn-main': No such file or directory
Done!
